[package]
name = "toml-targets"
version = "0.0.0"
publish = false

[dependencies]
toml = { git = "https://github.com/alexcrichton/toml-rs" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "read_toml"
path = "read_toml.rs"
