[package]
name = "deflate-targets"
version = "0.0.0"
publish = false

[dependencies]
deflate = { git = "https://github.com/oyvindln/deflate-rs", branch = "dev" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "compress"
path = "compress.rs"
