[package]
name = "brotli-targets"
version = "0.0.0"
publish = false

[dependencies]
brotli = { git = "https://github.com/dropbox/rust-brotli" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "read_bytes"
path = "read_bytes.rs"
