[package]
name = "chrono-targets"
version = "0.0.0"
publish = false

[dependencies]
chrono = { git = "https://github.com/chronotope/chrono" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "read_dates"
path = "read_dates.rs"
