[package]
name = "uuid-targets"
version = "0.0.0"
publish = false

[dependencies]
uuid = { git = "https://github.com/rust-lang-nursery/uuid" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "read_uuid"
path = "read_uuid.rs"
