[package]
name = "encoding_rs-targets"
version = "0.0.0"
publish = false

[dependencies]
encoding_rs = { git = "https://github.com/hsivonen/encoding_rs" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "read_text"
path = "read_text.rs"
