[package]
name = "regex-targets"
version = "0.0.0"
publish = false

[dependencies]
regex = { git = "https://github.com/rust-lang-nursery/regex" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "is_match"
path = "is_match.rs"
