[package]
name = "zopfli-targets"
version = "0.0.0"
publish = false

[dependencies]
zopfli = { git = "https://github.com/carols10cents/zopfli" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "compress"
path = "compress.rs"
